export const metadata = { title: 'Privacy Policy — TasklyClean' }

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 space-y-8">
      <div>
        <p className="text-sm font-medium uppercase tracking-widest text-blue-600 mb-2">Legal</p>
        <h1 className="text-4xl font-bold text-slate-900">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: March 31, 2026</p>
      </div>

      {[
        {
          title: '1. Information We Collect',
          body: `We collect information you provide directly (name, email, profile details), information generated by your use of the Platform (orders, messages, listings), and technical data (device type, IP address, browser) via cookies and analytics tools.`,
        },
        {
          title: '2. How We Use Your Information',
          body: `We use your data to operate the Platform, process transactions, send notifications, prevent fraud, improve our services, and communicate platform updates. We do not sell your personal information to third parties.`,
        },
        {
          title: '3. Data Sharing',
          body: `We share your information with service providers necessary to operate TasklyClean (payment processors, hosting, email delivery). In a transaction, sellers and buyers see each other's display names and order-related information. We may disclose data when required by law.`,
        },
        {
          title: '4. Cookies',
          body: `We use cookies to maintain sessions, remember preferences, and analyse Platform usage. You can manage cookie preferences through your browser settings. See our Cookie Policy for details.`,
        },
        {
          title: '5. Data Retention',
          body: `We retain your account data for as long as your account is active and as required by law. Transaction records are kept for a minimum of 7 years for compliance purposes.`,
        },
        {
          title: '6. Your Rights',
          body: `Depending on your location, you may have rights to access, correct, delete, or export your personal data. Contact us at privacy@tasklyclean.com to exercise these rights. We will respond within 30 days.`,
        },
        {
          title: '7. Security',
          body: `We implement industry-standard security measures including encryption, access controls, and regular security reviews. However, no system is completely secure — use strong, unique passwords and report suspicious activity immediately.`,
        },
        {
          title: '8. Children',
          body: `TasklyClean is not directed at children under 18. We do not knowingly collect personal information from minors. If you believe a minor has registered, contact us immediately.`,
        },
        {
          title: '9. Changes to This Policy',
          body: `We may update this Privacy Policy periodically. Material changes will be communicated via email or a prominent notice on the Platform. Continued use after changes constitutes acceptance.`,
        },
      ].map(s => (
        <section key={s.title}>
          <h2 className="text-lg font-bold text-slate-900 mb-2">{s.title}</h2>
          <p className="text-slate-600 leading-7">{s.body}</p>
        </section>
      ))}

      <div className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">
        Privacy questions? Contact us at <a href="mailto:privacy@tasklyclean.com" className="text-blue-600 hover:underline">privacy@tasklyclean.com</a>
      </div>
    </main>
  )
}
